# This file was generated by GoReleaser. DO NOT EDIT.
cask "run" do
  version "0.23"

  on_macos do
    on_arm do
      sha256 "5a12156a3353c04f10f2d754c07c8ac9e002b1b0a002a1bb879028163950c022"
      url "https://github.com/JulienBreux/run-cli/releases/download/v#{version}/run_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "599bf7b3ec1d599894881f8aa8ea8798ca0ae80f134d8e4bb89f2b8f18ebcafe"
      url "https://github.com/JulienBreux/run-cli/releases/download/v#{version}/run_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5b0fe88732016dc8bd8397da5129d4da7560d6f109c655aafaf40f97e6c4d6e7"
      url "https://github.com/JulienBreux/run-cli/releases/download/v#{version}/run_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4d3f6c31be9ecc1a5a1c2ea16d78c2b13661243de4bc079adc70b7e9c0888b08"
      url "https://github.com/JulienBreux/run-cli/releases/download/v#{version}/run_Linux_x86_64.tar.gz"
    end
  end

  name "run"
  desc "Run CLI is an interactive CLI to manage your Google Cloud Run resources with panache!"
  homepage "https://github.com/JulienBreux/run-cli/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "run"

  # No zap stanza required
end
